### ISSUE TITLE
Evolve 1.5(1.4.3) not opening on ubuntu 22.04

### ISSUE THREAD

**Issue by thusvill** [arcnations-united/evolve#7] opened 2024-07-14 02:14 UTC
I just downloaded it and executed install.sh and It installed perfectly without any bug.
But when I try to open the evolve, the terminal output this:
`./gtkthememanager: symbol lookup error: ./gtkthememanager: undefined symbol: g_once_init_enter_pointer`

Im trying to run this on ubuntu 22.04 
All other older versions worked for me without any problem.🥲

![image](https://github.com/user-attachments/assets/ecd83501-514c-4303-a489-865806217bac)

**Comment by arcnations-united** [comment] 2024-07-16 17:36
Evolve v1.5 is in Alpha. It is only compatible with Ubuntu 24.04, Fedora 40 or other distros running the same or later kernel and GNOME version. This happens with every release but support for older distros are added eventually. Please wait for a few more days. Thanks!

**Comment by arcnations-united** [comment] 2024-08-03 03:52
The issue is resolved in v1.5.1

**Closed** 2024-08-03 03:51 UTC
